Review tiles
rpp29-fec-cheddar/api pull request #41
Opened 2021-08-10 06:05 UTC by PBandJaimie

@a-nouraldean @EJLEE808 @Taniel-P 

I've made a lot of progress on the display of the review tiles, still quite a bit of work to go, however.

2021-08-11 22:13 UTC, Taniel-P commented on client/src/components/Reviews/Images.jsx
> +
The state is empty.  Should be src based on line 14?

2021-08-11 22:16 UTC, Taniel-P commented on client/src/components/Reviews/SingleTile.jsx
> +class SingleTile extends React.Component {
This is great!

2021-08-11 22:19 UTC, Taniel-P requested changes
This is great work!  There are so many edge cases for you widget it's crazy, but everything looks awesome! 

It is saying there is a merge conflict though, can you fix that before we merge with main.

2021-08-12 06:40 UTC, PBandJaimie commented
Just added scroll and button functionality.

2021-08-13 01:14 UTC, Taniel-P approved these changes
Changes look good!

2021-08-13 01:14 UTC, merged